version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
before_build:
  - npm install -g vsce
  - npm --version
  - node --version
build_script:
  - .\build.bat
after_build:
  - vsce package
  - dir
test: off
artifacts:
  - path: '*.vsix'
    name: Offline installer
